version: "3.8"

services:
  evcc:
    image: evcc/evcc:latest
    restart: unless-stopped
    command:
      - evcc
    networks:
      - evcc-net
    ports:
      - 8887:8887/tcp # used for OCPP (Open Charge Point Protocol)
      - 7090:7090/udp # used for special protocols like EEBus
      - 9522:9522/udp # used for special protocols like EEBus
    volumes:
      - ./evcc.yaml:/etc/evcc.yaml
      - evcc-data:/root/.evcc

  caddy:
    image: caddy:2
    restart: unless-stopped
    networks:
      - evcc-net
    ports:
      - 7070:7070 # The Caddy Port for APIs and Web UI
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs/server.crt:/config/server.crt
      - ./certs/server.key:/config/server.key
    environment:
      DOMAIN: "https://localhost"  # Your domain.

networks:
  evcc-net:
    driver: bridge

volumes:
  evcc-data:
